# Generated by Django 5.0.7 on 2025-02-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where', models.CharField(max_length=200)),
                ('arrivals', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('details', models.TextField()),
            ],
        ),
    ]
